In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

from model import KPRN
from model import train
from model import format_paths
from model import construct_ix_to_etr
from model import scores_from_paths

ImportError: cannot import name 'format_paths'

In [11]:
#For now some hardcoded paths
training_data = [
    ([['Sam', 'u', 'rate'], ['Song1', 's', 'category'], ['Pop', 't', '_belong'], ['Song2', 's', 'UNK']], 1),
    ([['Sam', 'u', 'rate'], ['Song2', 's', 'UNK']], 1),
    ([['Sam', 'u', 'rate'], ['Song1', 's', '_rate'], ['Joey', 'u', 'rate'],['Song3', 's', 'UNK']], 0),
    ([['Sam', 'u', 'rate'], ['Song1', 's', '_rate'], ['Song3', 's', 'UNK']], 0)
]

#For now just construct example, later would want to automatically create maps from vocab
e_to_ix = {'Sam': 0, 'Weijia': 1, 'Rosa': 2, 'Joey':3, 'Song1': 4, 'Song2': 5, 'Song3': 6, 'Pop': 7}
t_to_ix = {'u': 0, 's': 1, 't': 2}
r_to_ix = {'rate': 0, 'category': 1, 'belong': 2, '_rate': 3, '_category': 4, '_belong':5, 'UNK': 6}



In [14]:
formatted_data = format_paths(training_data, e_to_ix, t_to_ix, r_to_ix)
print(formatted_data)

In [15]:
model = train(formatted_data, e_to_ix, t_to_ix, r_to_ix)

loss is: 0.689369261264801
loss is: 0.76514732837677
loss is: 0.18956415355205536
loss is: 0.012585973367094994
loss is: 0.002468421822413802
loss is: 0.0013058000477030873
loss is: 0.0023395130410790443
loss is: 0.0010367024224251509
loss is: 0.0021105571649968624
loss is: 0.0009116546134464443
loss is: 0.0018938245484605432
loss is: 0.0009006972541101277
loss is: 0.0017486178549006581
loss is: 0.000895933189895004
loss is: 0.0016612252220511436
loss is: 0.0008818790083751082
loss is: 0.001612761989235878
loss is: 0.0008629412623122334
loss is: 0.0015740874223411083
loss is: 0.0008500776602886617


In [16]:
ix_to_etr = construct_ix_to_etr(e_to_ix, t_to_ix, r_to_ix)

scores_from_paths(model, formatted_data, 3, ix_to_etr)

paths and scores of form: [loss for tag 0, loss for tag 1]:

[['Sam', 'u', 'rate'], ['Song1', 's', 'category'], ['Pop', 't', '_belong'], ['Song2', 's', 'UNK']]
tensor([-6.4133e+00, -1.6410e-03])
[['Sam', 'u', 'rate'], ['Song1', 's', '_rate'], ['Joey', 'u', 'rate'], ['Song3', 's', 'UNK']]
tensor([-7.7992e-04, -7.1568e+00])
[['Sam', 'u', 'rate'], ['Song2', 's', 'UNK']]
tensor([-6.1153e+00, -2.2113e-03])
[['Sam', 'u', 'rate'], ['Song1', 's', '_rate'], ['Song3', 's', 'UNK']]
tensor([-8.3876e-04, -7.0840e+00])
